services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=http://localhost:8080
    networks:
      - rag_network

  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    networks:
      - rag_network
    platform: linux/arm64

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - backend/.env
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  ollama_data:
    driver: local
