name: Build Frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/build.yml"

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx vitest run
